---
title       : Body Fats Calculator
subtitle    : The Simple Way
author      : Lance Teo
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Why calculate Body Fats?

1. It is an indicator of your health as we need an optimal level of fats (Not too high and not too low)
2. Then you will know where you stands and work towards your target
3. To show off (if you have a good percentage of Body Fats)
4. And many more.. erm maybe not :P

---

## Why use this app to calculate?

1. It is usually hard to accurately calcualte Body Fats (using Caliper and stuff to pinch your body everywhere)
2. If not, the machine to calculate is usually too expensive for normal people to afford
3. Because this app is fast and accurate. You just need to spend 5 mins to measure yourself.
4. And because why not? I made it so use it. (though the formula is based on US Navy's formula)

---

## User Interface

Just key in your gender, height, weight, waist measurement, hip measurement and neck measurement and you are ready to go.

Click [HERE](https://lanceteo.shinyapps.io/App-1) for the Application
Click [HERE](https://github.com/lanceteo/Developing-Data-Products) for the Source Code

---


